# Generated by Django 3.1.6 on 2021-02-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('apparent_temperature_low', models.FloatField(blank=True, null=True)),
                ('lowest_temperature_today', models.FloatField(blank=True, null=True)),
                ('highest_temperature_today', models.FloatField(blank=True, null=True)),
                ('lowest_temperature_next_week', models.FloatField(blank=True, null=True)),
                ('highest_temperature_next_week', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
