# Generated by Django 3.1.6 on 2021-02-20 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherforecast', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherforecast',
            old_name='apparent_temperature_low',
            new_name='apparent_temperature',
        ),
    ]
